### ISSUE TITLE
`ngrok service start` failed on macos with agent v3.9

### ISSUE THREAD

**Issue by russorat** [ngrok/ngrok#1]
from: https://github.com/inconshreveable/ngrok/issues/950

I'm using ngrok with version 3.9.0 on MacOS
When I started ngrok service with the command `ngrok service start`, I got this error

> CRIT[05-02|09:22:06] start failed                             err="Failed to start ngrok: \"launchctl\" failed with stderr: Load failed: 5: Input/output error\nTry running `launchctl bootstrap` as root for richer errors.\n"

Please anyone can help me to fix this problem?

Regards.

**Comment by russorat** [comment]
fyi @chungbn

**Comment by chungbn** [comment]
Yes, it worked. Thank you for your help.

**Comment by bobzilladev** [comment]
Excellent, glad to hear it! I'll go ahead and close out this issue, feel free to reopen if something else comes up.
