### ISSUE TITLE
Possible to use ngrok on a single interface?

### ISSUE THREAD

**Issue by russorat** [ngrok/ngrok#10]
from @hook-s3c : https://github.com/inconshreveable/ngrok/issues/498

Sometimes I change NICs, or need to turn one of them off - and because of this ngrok seems to disconnect briefly.

Just wondering if there was an interface flag, or if one could be added?

**Comment by euank** [comment]
I believe this is the `connect_interface` option in the yml config file, which I think got added in `v3.0.0`.

There's a remark on it in the agent changelog, but otherwise undocumented as far as I can see.

Seems possible this one is just a documentation issue.

**Comment by russorat** [comment]
Thanks @euank ! i tried this on the latest ngrok agent v3.10 and saw a panic, so i opened an issue to fix.

**Comment by russorat** [comment]
the panic is now fixed in v3.10.1, and the `connect_interface` is only supported on linux (not macos where i was trying it). I will update our docs to include this config option.

**Comment by russorat** [comment]
added in https://github.com/ngrok/ngrok-docs/pull/786. Thanks!
