### ISSUE TITLE
The url has been identified as malicious and/or abusive.

### ISSUE THREAD

**Issue by ssh-sato** [ngrok/ngrok#12]
hello,
since this morning, i got this error when configuring webhook url with my facebook test app: 
The url has been identified as malicious and/or abusive. this was working fine 
tried to change region to us but same problem

**Comment by russorat** [comment]
Hi @ssh-sato , thanks for writing in. We've seen this in the past with some of our urls, but it seems to be very specific to the url and/or the top level domain. 

I recommend snagging your free static domain from https://dashboard.ngrok.com and using that instead of the randomly generated one.

**Comment by ssh-sato** [comment]
Hi @russorat, yes the url was with domain option,
the one i always use : ngrok http --domain=xxx-xxx-xxx.ngrok-free.app 3000

**Comment by Lizangulo** [comment]
I started to notice the same issue today and it wasn't happening before. I tried with a static domain and it didn't work

**Comment by russorat** [comment]
Thanks! What browser was this on?

**Comment by ssh-sato** [comment]
> Thanks! What browser was this on?

chromium and firefox ( ubuntu)
edge (windows)

i don't think this is a problem of browser, it's from facebook

**Comment by russorat** [comment]
We've been trying to open a bug report at facebook or in some way get in contact with them but any time we try to report a bug, we get an error. open to suggestions outside of trying to leverage personal contacts.

![image](https://github.com/ngrok/ngrok/assets/4805997/fc1342f1-f579-4545-a9e8-3df4899ff447)

**Comment by russorat** [comment]
What we have seen is there seems to be some sort of IP level blocking happening for our urls and custom domains.

**Comment by russorat** [comment]
Hi, we've gotten some updated reports that ngrok urls are no longer blocked here. either way, there's not much we can do to change it since we can't get in touch with anyone at meta. i'm closing this for now. thanks!
