### ISSUE TITLE
Godaddy domain dns adding error

### ISSUE THREAD

**Issue by thinkdave1** [ngrok/ngrok#14]
While adding a DNS record to my domain address that I purchased through Godaddy, even though I entered the correct information given by ngrok, it says the data entry is invalid and prevents me from opening a record. What is the reason?

**Comment by russorat** [comment]
@thinkdave1 thanks for the issue. Do you mind adding a screenshot of what you entered into godaddy and the error you are seeing?

**Comment by thinkdave1** [comment]
<img width="1275" alt="error" src="https://github.com/user-attachments/assets/f8fb1a0d-6188-48a8-8631-5549486eb2f3">

**Comment by russorat** [comment]
Hi @thinkdave1 , thank you for the screenshot. I do not think GoDaddy supports using the @ symbol when creating a cname record. You will need to register a domain with a subdomain (app.example.com) and use app instead of the @ symbol in godaddy. 

See https://ngrok.com/docs/network-edge/domains-and-tcp-addresses/#branded-domains

**Comment by russorat** [comment]
@thinkdave1 just following up here, were you able to get this working?

**Comment by thinkdave1** [comment]
No, I still haven't found the solution. I added a record as attached, but I cannot ping it. 
![Uploading errorngrok.png…]()

**Comment by russorat** [comment]
Does this guide help at all? https://github.com/ngrok/ngrok-docs/pull/766/files

**Comment by thinkdave1** [comment]
In this example, it shows a subdomain. I want to use the domain directly. Will this cause a problem?

**Comment by russorat** [comment]
Ah, ok, so CNAMEs can't be used for apex domains (what you're calling domain directly). here's more info: https://serverfault.com/questions/613829/why-cant-a-cname-record-be-used-at-the-apex-aka-root-of-a-domain

what i've done in the past here is register www.example.com and then use domain forwarding in godaddy to forward the root to www. the other option is to use cloudflare's dns which has cname flattening feature: https://blog.cloudflare.com/introducing-cname-flattening-rfc-compliant-cnames-at-a-domains-root/

**Comment by nijikokun** [comment]
@thinkdave1 just following up to see whether @russorat comment above satisfies your question and needs or if you still need any additional help, otherwise we will close this out as completed.

**Comment by russorat** [comment]
@thinkdave1 hi, since we haven't heard any follow ups, we're going to close this. If you are still having problems, please open a new issue. Thank you!
