### ISSUE TITLE
ngrok-server failed to read message: write tcp 172.23.35.49:4443->27.208.255.182:14288: write: connection reset by peer

### ISSUE THREAD

**Issue by liuxiaokaizi** [ngrok/ngrok#15]
ngrok-server: failed to read message: write tcp 172.23.35.49:4443->27.208.255.182:14288: write: connection reset by peer
ngrok-client: control recovering from failure read tcp 192.168.1.102:58496->118.31.114.85:4443: wsarecv: An existing connection was forcibly closed by the remote host

May I ask how to solve it？

**Comment by salilsub** [comment]
@liuxiaokaizi Could you provide a little more context on what you were doing? Were you using the agent, one of the SDKs? Could you provide the commands you used or a code snippet?

**Comment by liuxiaokaizi** [comment]
Hello, I would like to use ngrok to build intranet penetration. I installed ngrok on a public server and compiled the Linux server and Windows client. I want to penetrate the internal network to access certain services on my computer through the external network. After starting the public network server, there was an unstable connection issue when restarting the local client. The following are the relevant directories and screenshots.


ngrok
GOOS=linux GOARCH=amd64 make release-server
GOOS=windows GOARCH=amd64 make release-client








server startup

client startup

server





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ngrok/ngrok"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ngrok/ngrok] ngrok-server failed to read message: write tcp 172.23.35.49:4443-&gt;27.208.255.182:14288: write: connection reset by peer (Issue #15)





 
@liuxiaokaizi Could you provide a little more context on what you were doing? Were you using the agent, one of the SDKs? Could you provide the commands you used or a code snippet?

**Comment by russorat** [comment]
Hi @liuxiaokaizi, thanks for your comment. There is no open source ngrok server that is supported. To accomplish what you want to do, sign up for an account at http://ngrok.com and follow the instructions to get started.

**Comment by russorat** [comment]
i'm going to close this for now as it relates to legacy version of ngrok. thanks!
