### ISSUE TITLE
running ngrok in wsl gives the following error

### ISSUE THREAD

**Issue by velvet-jedi** [ngrok/ngrok#20]
![image](https://github.com/user-attachments/assets/efeb11d5-d44d-465b-a6c8-79ae463fe4f8)

Session Status                reconnecting (failed to send authentication request: failed to fetch CRL. errors encountered: timed out fetching CRL)

**Comment by velvet-jedi** [comment]
works when done through the command prompt (windows)

**Comment by russorat** [comment]
@velvet-jedi i am double checking with the team that there isn't some broader error with the CRL. For now, you can add `crl_noverify: true` to your config to skip this check.

**Comment by russorat** [comment]
@velvet-jedi were you ever able to get this working on wsl?

**Comment by russorat** [comment]
@velvet-jedi hi, since we haven't heard from you in a while, we're going to close this ticket. Please feel free to open a new issue if you're still having problems with wsl. Thank you!
