### ISSUE TITLE
I'm trying to connect in a Minecraft server but it isn't letting me

### ISSUE THREAD

**Issue by AvaniIsMonkey** [ngrok/ngrok#22]
![image](https://github.com/user-attachments/assets/2bb32448-f234-4f07-ad85-33fb50ab9965)

It clearly shows there that the IP is 0.tcp.eu.ngrok.io:15807 but when I try to join from it, I get errors like "Disconnected" or "Connection Resetted". As a matter of fact, the server can't be pinged either, it says, "Can't connect to the server" as the error. 

Please help me fix it!

**Comment by russorat** [comment]
@AvaniIsMonkey thanks for the issue. check out your usage page to see if there are any limits on your account: https://dashboard.ngrok.com/usage

**Comment by russorat** [comment]
Hi @AvaniIsMonkey, since we haven't heard back from you, i'm going to close this. Please open a new issue if you are still having trouble.
