### ISSUE TITLE
Ngrok can't connect to any port

### ISSUE THREAD

**Issue by crawlchange** [ngrok/ngrok#25]
Unable to connect

Firefox can’t establish a connection to the server at localhost:8080.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the web.

Please provide correct, reliable, up-to-date instructions on how to use ngrok.

**Comment by nijikokun** [comment]
Hi @crawlchange 👋 

Can you provide the following details so I can better debug whats going on:

- What is the URL that you are inputting into your Firefox browser bar
- What is the ngrok command that you ran in your terminal or if you are using another method the steps you took.

Any screenshots or terminal logs would also be nice to have to better help you get started.

**Comment by russorat** [comment]
Hi @crawlchange, since we haven't heard back from you, i'm going to close this. Please open a new issue if you are still having trouble.
