### ISSUE TITLE
connection fail

### ISSUE THREAD

**Issue by QiaoYang0923** [ngrok/ngrok#31]
Session Status                reconnecting (failed to send authentication request: read tcp 172.16.30.12:35734->18.141.102.200:443: wsarecv: An existing connection was forcibly closed by the remote host.)     
![image](https://github.com/user-attachments/assets/644bffa1-e0d0-4e6e-96ac-0379f5711bb4)

**Comment by joelhans** [comment]
Hi @QiaoYang0923! Thanks for reporting the issue, and sorry to hear ngrok isn't working for you straightaway.

Could you give me a few more pieces of information to help me point you in the right direction?

- How did you install the ngrok agent?
- What `ngrok ...` command are you running where you see this error?
- Does your network have any firewalls or proxies that might interfere with connecting to ngrok's network?

**Comment by QiaoYang0923** [comment]
hi,I use the.exe file on the window platform and download it from the official website. I run the` ngrok http http://localhost:8080 command and the ngrok tunnel --label Edge = edghts_2kxiWOSKWuKVxSMSajJfXin2pMd http://localhost:80`, these two commands appear this problem, my state of firewall is turned off, don't use the proxy

**Comment by joelhans** [comment]
Thanks for the information!

One thing to try is removing the `http://localhost:` from the commands you're running. All ngrok needs is the port your service is running on, like so:

```bash
ngrok http 8080

The same applies for the second command, but I also believe your `--label` should be referenced without whitespace:

```bash
ngrok tunnel --label edge=edghts_2kxiWOSKWuKVxSMSajJfXin2pMd 80
```

Let me know how you get along with those! If the error persists or change, we can try something else.

**Comment by QiaoYang0923** [comment]
Thank you, I tried to use the following command to run,  `ngrok http 3000` but there is still an error in the picture,I make sure that my service port is properly accessed locally; 
![image](https://github.com/user-attachments/assets/704c4625-6e15-49f9-a6a1-b3b46c61292a)
The second command I copied from this picture

**Comment by russorat** [comment]
@QiaoYang0923 hi, i noticed there was a typo in your original ngrok command: 

`ngrok http http://localhost:8080 command and the ngrok tunnel --label Edge = edghts_2kxiWOSKWuKVxSMSajJfXin2pMd http://localhost:80`

You should probably remove the last localhost:80, so it looks like:

`ngrok http http://localhost:8080 command and the ngrok tunnel --label Edge = edghts_2kxiWOSKWuKVxSMSajJfXin2pMd`

**Comment by russorat** [comment]
@QiaoYang0923 we haven't heard from you in a while. If you are still having trouble, please just add a comment and I will reopen.
