### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by Pogix3m** [ngrok/ngrok#33]
<img width="1037" alt="image" src="https://github.com/user-attachments/assets/a62ca314-1822-41cf-aba9-48e4f00f876e">

I've installed ngrok using `brew install ngrok/ngrok/ngrok`
I've also added the `authtoken` base on the setup & installation
I run using `ngrok http 3031`, I also tried `ngrok http http://localhost:3031` same result

**Comment by russorat** [comment]
Hi @Pogix3m, thank you for the issue. It looks like there's an issue with DNS where it can't find the domain. Are you still hitting this? If so, you can try flushing your DNS cache following these instructions: https://www.hostinger.com/tutorials/fix-dns_probe_finished_nxdomain#1_Flush_the_DNS_cache

**Comment by Pogix3m** [comment]
thank you @russorat 
after following the instructions, changing the DNS Servers is what worked for me
