### ISSUE TITLE
Ngrok URL not working locally on localhost:3000

### ISSUE THREAD

**Issue by suntay44** [ngrok/ngrok#38]
On other laptop the domain os working fine, but on my laptop where the localhost is it cannot be reached
```
This site can’t be reached
Check if there is a typo in 5baf-119-94-132-247.ngrok-free.app.
DNS_PROBE_FINISHED_NXDOMAIN
```

local setup is working I ran: `rails s -p 3000` and `ngrok config add-authtoken AUTH-TOKEN` in my ngrok i tried both `ngrok http 3000` and `ngrok http http://localhost:3000`

Installed using: `brew install ngrok/ngrok/ngrok`
MacOS: Ventura 13.2
Firewall is inactive

But still not working:
<img width="967" alt="Screenshot 2024-09-04 at 1 49 14 PM" src="https://github.com/user-attachments/assets/64eca606-6503-47e4-be2e-91a1388b2b7a">
<img width="937" alt="Screenshot 2024-09-04 at 1 49 18 PM" src="https://github.com/user-attachments/assets/53d1aa47-3797-4590-8d08-efc95b01eaf4">
<img width="725" alt="Screenshot 2024-09-04 at 1 49 22 PM" src="https://github.com/user-attachments/assets/af1615de-be53-47a6-89f1-a3c37865ebb9">

<img width="909" alt="Screenshot 2024-09-04 at 1 48 53 PM" src="https://github.com/user-attachments/assets/d73b48c0-79c2-42ef-9ed6-4b9a711307d7">

**Comment by russorat** [comment]
@suntay44 thanks for the issue. this looks similar to #33. Could you try those troubleshooting steps?

**Comment by suntay44** [comment]
thanks, same solution worked for me! 

> @suntay44 thanks for the issue. this looks similar to #33. Could you try those troubleshooting steps?
