### ISSUE TITLE
YAML parsing error How to fix in Kali linux / VM

### ISSUE THREAD

**Issue by Mrxmiracle** [ngrok/ngrok#40]
Gives error after any command of ngrok
Error :------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ERROR:  Error reading configuration file '/root/.config/ngrok/ngrok.yml': YAML parsing error: yaml: unmarshal errors:
ERROR:    line 2: field authtoken not found in type config.v3yamlConfig

**Comment by davetapley** [comment]
Probably dupe of:
- https://github.com/ngrok/ngrok/issues/34

**Comment by russorat** [comment]
yep! 3.16 was released earlier today so you should be able to fix by upgrading.
