### ISSUE TITLE
auth with github is not working, just keep getting redirected to login page

### ISSUE THREAD

**Issue by da1z** [ngrok/ngrok#42]

**Comment by da1z** [comment]
@russorat i was not able to create account with GitHub or google auth, ended up creating with email. Looks like issue not just related to github. I was just throwing back to signup page every time

**Comment by russorat** [comment]
@da1z thanks for your patience. engineering let me know that they think they've rolled out a fix to address this if you want to try it.

**Comment by russorat** [comment]
We believe we fixed this issue. I'm going to close this for now and if you still see it, please open a new issue. thanks!

**Comment by Zwnow** [comment]
If it was fixed, it's broken again. Github and Google Signup and Login not working.
