### ISSUE TITLE
trojan detected after upgrade ngrok to 2.3.41 in windows

### ISSUE THREAD

**Issue by cuttingedge1109** [ngrok/ngrok#43]
I have been using ngrok personal plan for a few years.
I used to upgrade its version by `Ctrl+U` when update is recommended by ngrok itself.
Now the current version is `2.3.25` and `2.3.41` is available. Once i upgrade it, windows security center detects trojan.

![image](https://github.com/user-attachments/assets/414fe269-691a-4939-ad49-09a393a973a7)

**Comment by russorat** [comment]
@cuttingedge1109 thanks for the report. It's a false positive. The latest ngrok agent version is v3.16.0 which has been scanned and approved by microsoft. 

![image](https://github.com/user-attachments/assets/843da146-0800-4b12-8fb0-3afd4fb7aa36)

**Comment by russorat** [comment]
@cuttingedge1109 hi, were you able to upgrade to the latest v3.16.0 agent version?

**Comment by cuttingedge1109** [comment]
> @cuttingedge1109 hi, were you able to upgrade to the latest v3.16.0 agent version?

@russorat i didn't know v3.x exists. I will test today

**Comment by cuttingedge1109** [comment]
The latest ngrok agent version v3.16.0 looks good.
