### ISSUE TITLE
Pre-visit page prevents using websockets from a free account.

### ISSUE THREAD

**Issue by smhanov** [ngrok/ngrok#46]
The pre-visit page interferes with websockets, breaking the protocol. The page suggests changing request headers, but this is not possible to do using the websockets API.

Reproduction steps:
1. Set up a basic websocket server using, eg,  websocat:

    sudo wget -qO /usr/local/bin/websocat https://github.com/vi/websocat/releases/latest/download/websocat.x86_64-unknown-linux-musl
    sudo chmod a+x /usr/local/bin/websocat

    websocat -s 8080

2. Start ngrok. Important: Use an API token from an account created after 2022.
    ngrok http 8080

3. Inside a web browser javascript console, attempt to open a web socket to the ngrok url:

    let a = new WebSocket("wss://your-ngrok-url.ngrok-free.app")

Result: "WebSocket connection to 'wss://8406-129-97-124-23.ngrok-free.app/' failed:" (there is no further information given in the error)

4. Install a browser extension "User agent switcher and Manager" and change user agent for all tabs to "test"

5. Enter in javascript console:

    let b = new WebSocket("wss://your-ngrok-url.ngrok-free.app")

Result: no error

Changing the user agent header allows it to work, but this is not possible without installing a browser extension. Unlike fetch/XMLHTTPRequest, is not possible to add or change any header when opening a websocket.

Suggested solution:
Preferred: When the Upgrade header contains websocket, do not show the pre-visit page, since it would be impossible to view it anyway.

Or: Update https://ngrok.com/docs/using-ngrok-with/websockets/ to make it clear that websockets are not supported without a paid account.

**Comment by russorat** [comment]
@smhanov thanks for the issue. this is a bug, not intentional. Let me chat with eng and get this fixed.

**Comment by russorat** [comment]
we should have a fix for this deployed in the next 24 hours. thanks again for reporting!

**Comment by russorat** [comment]
this should be rolled out now. let us know if you're still having issues. thanks again!
