### ISSUE TITLE
No space between timezone and method

### ISSUE THREAD

**Issue by danielcompton** [ngrok/ngrok#52]
For countries with a 4 letter timezone code, the timezone and HTTP request method are right together with no space.

<img width="462" alt="ScreenFloat Shot of iTerm2 at 13 Oct 2024 at 7_48_03 AM" src="https://github.com/user-attachments/assets/2f3ceb94-f930-4298-a7ce-491de185dc13">

**Comment by russorat** [comment]
@danielcompton thanks for this! I'll get this fixed

**Comment by russorat** [comment]
@danielcompton thanks for this. we were able to get a fix in and it should show up in the next agent release. we usually do those on thursdays.
