### ISSUE TITLE
Binary on mac os keeps getting deleted

### ISSUE THREAD

**Issue by Varsneya** [ngrok/ngrok#62]
Ngrok binary gets deleted when I follow the setup process. This is on mac Apple M2 Max, macOs Sequoia 15.1.1

**Comment by russorat** [comment]
@Varsneya thanks for the issue! usually this is due to antivirus software. could that be the case? if so, do you mind sharing the name and version of the software?

**Comment by Varsneya** [comment]
Thanks for the quick response @russorat. I am not using any anitvirus software as such. Is it something by default on mac os? A newbie to mac world, if so how can I disable this. Because I am able to download the arm binary and add it on /usr/local/bin but when I try to setup the token for ngrok zsh kills it and deletes the binary.

**Comment by Varsneya** [comment]
I am able to run it through docker but would make my life a lot easier if it can work through the cli as it used to before. 
Thank you

**Comment by russorat** [comment]
i know on mac there can be issues with some command line apps. In Settings > Privacy & Security > Security, sometimes it will block applications from running, but i've never heard of the being deleted. 

if you're new to the mac world, it might be easier to install homebrew ( https://brew.sh/ )  and install ngrok through `brew install ngrok/ngrok/ngrok`. that way it will update your path and ensure the binary is in the right spot.

**Comment by Varsneya** [comment]
I have tried through brew as well, it still kills the executable. brew install ngrok/ngrok/ngrok
<img width="455" alt="image" src="https://github.com/user-attachments/assets/e4dd49f5-6407-4bda-91a1-64cbbbbc1054">

**Comment by russorat** [comment]
have you been able to try this? https://support.apple.com/en-us/102445#openanyway

**Comment by Varsneya** [comment]
It doesn't prompt me to allow ngrok to run in any way.

**Comment by yukonhenry** [comment]
I have the same issue, M1 Pro, macos Sequoia 15.0; problem occurs whether installing via brew or directly binary download; tried also with 'Allow applications from  - Anywhere' in Settings: Privay&Security.  This problem only started to less than 2 days ago after successful usage the last several months.

**Comment by rukumar333** [comment]
I also have the same issue on Mac M3 Max Sonoma 14.7.1.

**Comment by dthomasngrokker** [comment]
Could you all please try installing via brew, but instead of running `brew install ngrok/ngrok/ngrok` just run `brew install ngrok`?

I am on a MacBook Air, Apple M2, Sequoia 15.1 



<img width="844" alt="Screenshot 2024-11-21 at 10 03 10 AM" src="https://github.com/user-attachments/assets/f49e533b-2a14-47c7-b1ec-c29fef891cdb">

**Comment by rukumar333** [comment]
That seems to have fixed it for me. Thank you!

**Comment by Varsneya** [comment]
Yep this worked!
