### ISSUE TITLE
ngrok fails to resolve localhost

### ISSUE THREAD

**Issue by SkyJumper409x** [ngrok/ngrok#65]
I am trying to test an app locally, I have my app listening on localhost, port 3000.
ngrok can start, but the url can't be reached.
Opening the URL given to me by ngrok yields Error `ERR_NGROK_8012`.
The error it encountered was:
`dial tcp: lookup localhost on 1.1.1.1:53: no such host`
(`1.1.1.1` was my secondary DNS server, but I already removed it, so that's already odd.)
The only fix I found while researching was to run `ngrok http https://127.0.0.1:[port] --host-header=127.0.0.1:[port]`, instead of `ngrok http [port]`.
The problem with that fix is that my local server is listening on ipv6 `*:3000`, but when I try to put the ipv6 localhost address (`::1`) instead of the ipv4 localhost address (so the command is `ngrok http https://::1:3000 --host-header=::1:3000`), I get the error `ERR_NGROK_8012`, with the error ngrok encountered being the following:
`dial tcp: address ::1:3000: too many colons in address`
My OS is Arch Linux, using the AUR ngrok package with ngrok version 3.18.4 and package version 3.18.4-1.

**Comment by russorat** [comment]
hi @SkyJumper409x, thanks for the issue!

re: host-header, i think you can use `--host-header=rewrite` which will automatically update the host header to the right value. 

re: ipv6 localhost address
i think that might be a bug in the ngrok agent. I'll send it to the team to see what they think.

**Comment by russorat** [comment]
oops, actually, the info on how to use ipv6 with the agent is here: https://ngrok.com/docs/agent/#forwarding-to-ipv6-address

`ngrok http '[::1]: 3000' --host-header=rewrite`

**Comment by SkyJumper409x** [comment]
This did the trick for me with the space between the ip and port being removed, e.g. the command that works is `ngrok http '[::1]:3000' --host-header=rewrite`.

**Comment by russorat** [comment]
glad to hear!
