### ISSUE TITLE
page unable to load due to mixed content (tried on several browsers)

### ISSUE THREAD

**Issue by JosephBARBIERDARNAL** [ngrok/ngrok#66]
Hi!

When I go to the online page, it's empty (white). I've tried with other browsers and the console displays a message:

Safari: `[blocked] The page at https://01ad-2a01-e0a-18c-6440-588-3184-e4e1-e2fe.ngrok-free.app/ was not allowed to run insecure content from ws://01ad-2a01-e0a-18c-6440-588-3184-e4e1-e2fe.ngrok-free.app/.`

Firefox: `Uncaught DOMException: The operation is insecure.
    <anonymous> https://01ad-2a01-e0a-18c-6440-588-3184-e4e1-e2fe.ngrok-free.app/web/livecode/livecode.js:1`
    
Opera: `livecode.js:1 Mixed Content: The page at 'https://01ad-2a01-e0a-18c-6440-588-3184-e4e1-e2fe.ngrok-free.app/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://01ad-2a01-e0a-18c-6440-588-3184-e4e1-e2fe.ngrok-free.app/'. This request has been blocked; this endpoint must be available over WSS.
(anonymous) @ livecode.js:1
livecode.js:1 Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at livecode.js:1:10`
    

Feel free to ask for more info!

**Comment by JosephBARBIERDARNAL** [comment]
From what I understand is that: browsers don't like when we try to load content via http in an https page. See:

- https://stackoverflow.com/questions/39076180/https-page-was-not-allowed-to-run-insecure-content-from-safari-extension-uri
- https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by russorat** [comment]
@JosephBARBIERDARNAL thanks for the issue. Is it possible to load your websocket over wss?

**Comment by JosephBARBIERDARNAL** [comment]
Thanks for your quick reply @russorat 

I was trying to follow [this tuto](https://bitsandbricks.github.io/post/code-live-from-rstudio-and-share-it-with-the-world-in-real-time/#:~:text=Sharing%20our%20code%20live%20with,of%20typing%20a%20single%20line.) to do live coding in `R`. It relies on the [livecode R package](https://github.com/rundel/livecode)

After making a few adjustments to this `R` tool, I believe the issue originates from this package rather than ngrok. It seems to be working smoothly with ngrok now, so feel free to close this issue if that works for you!

**Comment by russorat** [comment]
great! thanks for confirming!
