### ISSUE TITLE
Console: Repeated requests cannot be distinguished from each other

### ISSUE THREAD

**Issue by russorat** [ngrok/ngrok#8]
from @iandunn : https://github.com/inconshreveable/ngrok/issues/838

> It'd help to include a timestamp, or some other unique way to tell them apart.
> Including the IP of the requester would be nice too

![image](https://github.com/ngrok/ngrok/assets/4805997/dba153cc-5c23-4dbd-a898-dfc275504cda)

**Comment by russorat** [comment]
connect @cjba7 https://github.com/inconshreveable/ngrok/issues/291

**Comment by sarvalabs-bhavyatomar** [comment]
Please bring this feature, its really annoying to guess when the request was made 🫡

**Comment by russorat** [comment]
this has been added to the standalone ngrok agent as of v3.11. Please upgrade and let us know what you think.

<img width="686" alt="image" src="https://github.com/ngrok/ngrok/assets/4805997/7021b25d-aee8-49ee-a8fd-39e882588baa">

**Comment by sarvalabs-bhavyatomar** [comment]
Works very well, thanks ngrok team!!!
